image:
  file: .gitpod.Dockerfile
tasks:
  - command: mkdir -p /workspace/data && mongod --dbpath /workspace/data
  - init: |
      cp .env.docker .env
      cp secret.example.yaml secret.yaml
      chmod +x ./start-mongodb.sh
      ./start-mongodb.sh latest "" 27019 testfish Mike fishtest 
      npm install
      npm run test

  - command: docker-compose up -d --build
    openMode: split-right

      
ports:
  # response of root request will be appeared in the browser
  - port: 3000
    name: root response
    onOpen: open-browser
    visibility: public


