apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
data:
  MONGO_USERNAME: bWlrZQ==        # base64 of mongodb user name 'mike', varies every time
  MONGO_PASSWORD: cHdkMTIz        # base64 of mongodb user password 'pwd123', varies every time